import {
  gray,
  grayA,
  grayDark,
  grayDarkA,
  mauve,
  mauveDark,
  mauveA,
  mauveDarkA,
  slateDarkA,
  slateA,
  slateDark,
  slate,
  sageDarkA,
  sageA,
  sageDark,
  sage,
  oliveDarkA,
  oliveA,
  oliveDark,
  olive,
  sand,
  sandA,
  sandDark,
  sandDarkA,
  bronze,
  bronzeA,
  bronzeDark,
  bronzeDarkA,
  gold,
  goldA,
  goldDark,
  goldDarkA,
  brown,
  brownA,
  brownDark,
  brownDarkA,
  orange,
  orangeA,
  orangeDark,
  orangeDarkA,
  tomato,
  tomatoA,
  tomatoDark,
  tomatoDarkA,
  red,
  redA,
  redDark,
  redDarkA,
  ruby,
  rubyA,
  rubyDark,
  rubyDarkA,
  crimson,
  crimsonA,
  crimsonDark,
  crimsonDarkA,
  pink,
  pinkA,
  pinkDark,
  pinkDarkA,
  plum,
  plumA,
  plumDark,
  plumDarkA,
  purple,
  purpleA,
  purpleDark,
  purpleDarkA,
  violet,
  violetA,
  violetDark,
  violetDarkA,
  iris,
  irisA,
  irisDark,
  irisDarkA,
  indigo,
  indigoA,
  indigoDark,
  indigoDarkA,
  blue,
  blueA,
  blueDark,
  blueDarkA,
  cyan,
  cyanA,
  cyanDark,
  cyanDarkA,
  teal,
  tealA,
  tealDark,
  tealDarkA,
  jade,
  jadeA,
  jadeDark,
  jadeDarkA,
  green,
  greenA,
  greenDark,
  greenDarkA,
  grass,
  grassA,
  grassDark,
  grassDarkA,
  sky,
  skyA,
  skyDark,
  skyDarkA,
  mint,
  mintA,
  mintDark,
  mintDarkA,
  lime,
  limeA,
  limeDark,
  limeDarkA,
  yellow,
  yellowA,
  yellowDark,
  yellowDarkA,
  amber,
  amberA,
  amberDark,
  amberDarkA,
} from "@radix-ui/colors";

export const allRadixPalettes = {
  gray: {
    light: gray,
    dark: grayDark,
    lightA: grayA,
    darkA: grayDarkA,
  },
  mauve: {
    light: mauve,
    dark: mauveDark,
    lightA: mauveA,
    darkA: mauveDarkA,
  },
  slate: {
    light: slate,
    dark: slateDark,
    lightA: slateA,
    darkA: slateDarkA,
  },
  sage: {
    light: sage,
    dark: sageDark,
    lightA: sageA,
    darkA: sageDarkA,
  },
  olive: {
    light: olive,
    dark: oliveDark,
    lightA: oliveA,
    darkA: oliveDarkA,
  },
  sand: {
    light: sand,
    dark: sandDark,
    lightA: sandA,
    darkA: sandDarkA,
  },
  bronze: {
    light: bronze,
    dark: bronzeDark,
    lightA: bronzeA,
    darkA: bronzeDarkA,
  },
  gold: {
    light: gold,
    dark: goldDark,
    lightA: goldA,
    darkA: goldDarkA,
  },
  brown: {
    light: brown,
    dark: brownDark,
    lightA: brownA,
    darkA: brownDarkA,
  },
  orange: {
    light: orange,
    dark: orangeDark,
    lightA: orangeA,
    darkA: orangeDarkA,
  },
  tomato: {
    light: tomato,
    dark: tomatoDark,
    lightA: tomatoA,
    darkA: tomatoDarkA,
  },
  red: {
    light: red,
    dark: redDark,
    lightA: redA,
    darkA: redDarkA,
  },
  ruby: {
    light: ruby,
    dark: rubyDark,
    lightA: rubyA,
    darkA: rubyDarkA,
  },
  crimson: {
    light: crimson,
    dark: crimsonDark,
    lightA: crimsonA,
    darkA: crimsonDarkA,
  },
  pink: {
    light: pink,
    dark: pinkDark,
    lightA: pinkA,
    darkA: pinkDarkA,
  },
  plum: {
    light: plum,
    dark: plumDark,
    lightA: plumA,
    darkA: plumDarkA,
  },
  purple: {
    light: purple,
    dark: purpleDark,
    lightA: purpleA,
    darkA: purpleDarkA,
  },
  violet: {
    light: violet,
    dark: violetDark,
    lightA: violetA,
    darkA: violetDarkA,
  },
  iris: {
    light: iris,
    dark: irisDark,
    lightA: irisA,
    darkA: irisDarkA,
  },
  indigo: {
    light: indigo,
    dark: indigoDark,
    lightA: indigoA,
    darkA: indigoDarkA,
  },
  blue: {
    light: blue,
    dark: blueDark,
    lightA: blueA,
    darkA: blueDarkA,
  },
  cyan: {
    light: cyan,
    dark: cyanDark,
    lightA: cyanA,
    darkA: cyanDarkA,
  },
  teal: {
    light: teal,
    dark: tealDark,
    lightA: tealA,
    darkA: tealDarkA,
  },
  jade: {
    light: jade,
    dark: jadeDark,
    lightA: jadeA,
    darkA: jadeDarkA,
  },
  green: {
    light: green,
    dark: greenDark,
    lightA: greenA,
    darkA: greenDarkA,
  },
  grass: {
    light: grass,
    dark: grassDark,
    lightA: grassA,
    darkA: grassDarkA,
  },
  sky: {
    light: sky,
    dark: skyDark,
    lightA: skyA,
    darkA: skyDarkA,
  },
  mint: {
    light: mint,
    dark: mintDark,
    lightA: mintA,
    darkA: mintDarkA,
  },
  lime: {
    light: lime,
    dark: limeDark,
    lightA: limeA,
    darkA: limeDarkA,
  },
  yellow: {
    light: yellow,
    dark: yellowDark,
    lightA: yellowA,
    darkA: yellowDarkA,
  },
  amber: {
    light: amber,
    dark: amberDark,
    lightA: amberA,
    darkA: amberDarkA,
  },
} satisfies Record<
  RadixGrayScale | AllRadixBrandScales,
  {
    light: Record<string, string>;
    dark: Record<string, string>;
    lightA: Record<string, string>;
    darkA: Record<string, string>;
  }
>;

export const radixGrayScales = [
  "gray",
  "mauve",
  "slate",
  "sage",
  "olive",
  "sand",
] as const;
export type RadixGrayScale = (typeof radixGrayScales)[number];

// These are the brand scales that have a light foreground (scale 12 in dark mode) (scale 1 in light mode)
export const radixBrandScalesWithLightForeground = [
  "bronze",
  "gold",
  "brown",
  "orange",
  "tomato",
  "red",
  "ruby",
  "crimson",
  "pink",
  "plum",
  "purple",
  "violet",
  "iris",
  "indigo",
  "blue",
  "cyan",
  "teal",
  "jade",
  "green",
  "grass",
] as const;
export type RadixBrandScaleWithLightForeground =
  (typeof radixBrandScalesWithLightForeground)[number];

// These are the brand scales that have a dark foreground (scale 12 in light mode) (scale 1 in dark mode)
const radixBrandScalesWithDarkForeground = [
  "sky",
  "mint",
  "lime",
  "yellow",
  "amber",
] as const;
type RadixBrandScaleWithDarkForeground =
  (typeof radixBrandScalesWithDarkForeground)[number];

export type AllRadixBrandScales =
  | RadixBrandScaleWithLightForeground
  | RadixBrandScaleWithDarkForeground;

export const naturalPairings = {
  gray: [
    ...radixBrandScalesWithLightForeground,
    ...radixBrandScalesWithDarkForeground,
  ],
  mauve: [
    "tomato",
    "red",
    "ruby",
    "crimson",
    "pink",
    "plum",
    "purple",
    "violet",
  ],
  slate: ["iris", "indigo", "blue", "cyan", "sky"],
  sage: ["mint", "teal", "jade", "green"],
  olive: ["grass", "lime"],
  sand: ["amber", "yellow", "orange", "brown"],
} satisfies Record<RadixGrayScale, Array<AllRadixBrandScales>>;

const destructiveColors = ["red", "ruby", "tomato"] as const;
export type DestructiveColor = (typeof destructiveColors)[number];

export const destructivePairings = {
  bronze: "red",
  gold: "red",
  brown: "red",
  orange: "tomato",
  tomato: "tomato",
  red: "red",
  ruby: "ruby",
  crimson: "ruby",
  pink: "ruby",
  plum: "ruby",
  purple: "ruby",
  violet: "ruby",
  iris: "ruby",
  indigo: "ruby",
  blue: "ruby",
  cyan: "ruby",
  teal: "ruby",
  jade: "red",
  green: "red",
  grass: "red",
  sky: "red",
  mint: "ruby",
  lime: "tomato",
  yellow: "tomato",
  amber: "tomato",
} satisfies Record<AllRadixBrandScales, DestructiveColor>;


